### ISSUE TITLE
Change Github structure to indra_lab being the "master" repository

### ISSUE THREAD

**Issue by kkaris** [johnbachman/depmap_analysis#20]
Currently, the fork structure is:

`johnbachman/depmap_analysis`
---- `kkaris/depmap_analysis`
---- **`indralab/depmap_analysis`**
---- bgyori/depmap_analysis

Suggesting to change it to:
**`indralab/depmap_analysis`**
---- `kkaris/depmap_analysis`
---- `johnbachman/depmap_analysis`
---- `bgyori/depmap_analysis`

**Comment by kkaris** [comment]
It's not urgent, but it's a bit odd to have to file issues to `johnbachman/depmap_analysis` but do everything else on `indralab/depmap_analysis` as per attached images:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
![indralab_no_issue](https://user-images.githubusercontent.com/4621351/46872680-da264e00-ce02-11e8-96b4-a7980664c252.png)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
![johns_repo_issue](https://user-images.githubusercontent.com/4621351/46872839-4012d580-ce03-11e8-88d3-5c93af2a1431.png)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by johnbachman** [comment]
Enabled issues on the indralab repo.
